name: TryHackMe Update Badge

on:
  schedule:
    # Make it run every 24 hour
    - cron: '0 0 * * *'
  workflow_dispatch:
jobs:
  tryhackme-badge-update:
    name: Update this repo's tryhackme badge with the latest tryhackme image badge
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: p4p1/tryhackme-badge-workflow@main
        with:
          # Replace with your tryhackme username
          username: "CoffeyHacks"
          GITHUB_TOKEN: ${{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}}